bashah/accounts/urls.py
from django.urls import path
from accounts import views

app_name = "account"

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register')
]

bashah/bashah/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('shop/', include('shop.urls')),
    path('collect/', include('collection.urls', namespace='collect')),
]

bashah/collection/urls.py
from django.urls import path
from collection import views

app_name = 'collection'

urlpatterns = [
    path('<int:product_id>/', views.collection_view, name='collect'),
#    path('category/<slug:slug>/', views.home, name='category_filter'),
#    path('<slug:slug>/', views.product_detail, name='product_detail'),
]

bashah/shop/urls.py
from django.urls import path
from shop import views
app_name = 'shop'
urlpatterns = [
    path('', views.cat_view, name='home'),
#    path('category/<slug:slug>/', views.cat_view, name='category_selected'),
    path('<slug:slug>/', views.detail, name='detail'),
#    path('/', views.detail, name='datail')
]

bashah/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from accounts.managers import MyUserManager


class User(AbstractBaseUser):
    email = models.EmailField(max_length=100, unique=True)
    full_name = models.CharField(max_length=100, default=None)
    phone_number = models.CharField(max_length=100, default=None)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name', 'phone_number']

    def __str__(self):
        return self.email

bashah/collection/models.py
from django.db import models
from shop.models import Product

# Create your models here.

class Collection(models.Model):
	product_ids = models.IntegerField()
	def collect(self,product_id):
		try:
			collection = self.objects.get(product_ids=product_id)
		except self.DoesNotExist:
			collection = self(product_ids=product_id)
			collection.save()
	def __int__(self):
		return self.product_ids

bashah/shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True,)
    is_sub = models.BooleanField(default=False)
    is_available = models.BooleanField(default=False)
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='sub_categories', null=True,
                                     blank=True)                                      
    def get_url(self):
# the whole args and slug thing
        return reverse('shop:category_selected', args={self.slug})
    def __str__(self):
        return self.name        
                                            
class Product(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
	name = models.CharField(max_length=200)
	slug = models.SlugField(max_length=100)
	detail = models.TextField()
	price = models.IntegerField()
	is_available = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	
	def __str__(self):
		return self.name

	def get_url(self):
		return reverse('shop:detail', args={self.slug, })
	def collect(self,Product_id):
		collection.append(Product_id)
		collection.super.save()
		

bashah/accounts/forms.py
from django import forms
from accounts.models import User
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'full_name', 'phone_number')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise forms.ValidationError('passwords must match')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'full_name', 'phone_number')

    def clean_password(self):
        return self.initial['password']


class UserLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegistrationForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(max_length=12,widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

bashah/collection/forms.py
from django import forms

class Collect(forms.Form):
	quantity = forms.IntegerField(min_value=1, max_value=9, widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                            'placeholder': 'quantity'}))
                                                                                                                                                                       

bashah/accounts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from accounts.forms import UserLoginForm, UserRegistrationForm
from accounts.models import User


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(request, email=data['email'], password=data['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'login successfully', 'success')
                return redirect('shop:home')
            else:
                messages.error(request, 'username or password is wrong', 'danger')
    else:
        form = UserLoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def user_logout(request):
    logout(request)
    messages.success(request, 'logout successfully', 'success')
    return redirect('shop:home')


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(data['email'], data['full_name'], data['phone_number'], data['password'])
            #this shit won't happen
            login(request, user)
            #but this will!
            messages.success(request, 'you registered successfully', 'success')
            return redirect('shop:home')
    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'form': form})

bashah/collection/views.py
from django.shortcuts import render
from django.http import HttpResponse
from shop.models import Product
from .models import Collection
# Create your views here.

def collection_view(request, product_id):
	Collection.collect(Collection, product_id)
	collection = Collection.objects.all()
	product = Product.objects.all()
	context = { 'collection' : collection, 'product' : product}
	return render(request, 'collection/collection.html', context)

bashah/shop/views.py
from django.shortcuts import render, get_object_or_404
from shop.models import Product, Category
from django.http import HttpResponse
# Create your views here.

def cat_view(request, slug=None):
	categories = Category.objects.filter(is_sub=False, is_available=True)
	products =  Product.objects.all()
	context ={'categories':categories, 'products':products,}    
	return render(request, 'shop/cat_view.html', context) 
	
def detail(request, slug):
	product = get_object_or_404(Product, slug=slug)
	context = {'product':product}
	return render(request, 'shop/detail.html', context) 

bashah/accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block title-head %}
    Login Page
{% endblock %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Login">
    </form>
{% endblock %}

bashah/accounts/templates/accounts/register.html
{% extends 'base.html' %}


{% block title-head %}
    Register Page
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Register">
    </form>
{% endblock %}

bashah/collection/templates/collection/collection.html
{% extends 'base.html' %}

{% block title %}
    collection
{% endblock %}

{% block title-head %}
	Here is your collection

{% endblock %}

{% block content %}
	{% for c in collection %}
		{% for p in product %}
			{% if c.product_ids == p.id %}
				<p> {{p.name}} </p>
	    		<p>{{ p.detail}} </p>
    			<p>{{ p.price }}</p>
			{% endif %}
		{% endfor %}	
	{% endfor %}	
{% endblock %}

bashah/shop/templates/shop/cat_view.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %} Bashah Online Shop{% endblock %}</title>
</head>

<body>
{% block content %}
	<p> Select a category </p>
	
	{% for cat in categories %}
    <ul>
        <p> <li> {{cat.id}}) {{cat.name}} </li></p>  
        <ul>
        	{% for pro in products %}
        	{% if pro.category == cat %}
        	<p><li> <a href= "{{pro.get_url}}"> {{pro.name}} </a> </li></p>        	
        	{% endif %}
        	{% endfor %}
        </ul>   	
    </ul>
    {% endfor %}  
          
{% endblock %}
</body>
</html>

bashah/shop/templates/shop/detail.html
{% extends 'base.html' %}
{% block content %}
    <h3>{{ product.name }} </h3>
    <p>{{ product.detail}} </p>
    <p>{{ product.price }} Dollar</p>
    <form action="{% url 'collection:collect' product.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-primary" value="Collect!">
    </form>
{% endblock %}

bashah/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <!-- CSS only -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    {% block custom_tags %}{% endblock %}

</head>
<body>

{% include 'layouts/navbar.html' %}

<div class="bg-light p-5 rounded-lg m-3">
    {% include 'external/messages.html' %}
    <h1 class="display-4"> {% block title-head %} {% endblock %}</h1>
    <p class="lead"> {% block lead %} {% endblock %}</p>
    <p> {% block content %} {% endblock %}</p>
</div>



<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>

{% block script %}
{% endblock %}
</body>
</html>

bashah/templates/external/messages.html
{% if messages  %}
    {% for message in messages %}
        <p class="alert alert-{{ message.tags }}">{{ message }}</p>
    {% endfor %}

{% endif %}

bashah/templates/layouts/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="container-fluid">
            <div class="navbar-nav">
<!---                <a class="nav-item nav-link" href="{% url 'shop:home' %}">Home</a> --->
                {% if request.user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:register' %}">Register</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>